### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Deshdeepak1** [MrStark-XD/Edu-Mail-Generator#2]
Error - Message: Process unexpectedly closed with status 1

**Comment by crackplatoonbd** [comment]
![image](https://user-images.githubusercontent.com/67650523/125486511-4a51c3ad-78ca-4cd3-871a-c5c5acdbcd70.png)
![image](https://user-images.githubusercontent.com/67650523/125486606-5fc7c843-65e4-4682-86bb-4c096d116b28.png)

ERROR
A proxy connection has been detected. To connect to California Community Colleges you must disable anonymizing services. This may include:
Tor web browser
VPN connections
Anonymizing browser plugins

**Comment by MrStark-XD** [comment]
check now

**Comment by terapapajani** [comment]
not working
![Screenshot 2021-12-14 234743](https://user-images.githubusercontent.com/93859919/146060833-68726016-f1bb-449b-86a3-5fce6570bf67.png)
