### ISSUE TITLE
ERROR A proxy connection has been detected. To connect to California Community Colleges you must disable anonymizing services. This may include: Tor web browser VPN connections Anonymizing browser plugins

### ISSUE THREAD

**Issue by crackplatoonbd** [MrStark-XD/Edu-Mail-Generator#3]
![image](https://user-images.githubusercontent.com/67650523/125486779-b1177cbf-b983-44ff-9d06-2f0effc8cf1a.png)
![image](https://user-images.githubusercontent.com/67650523/125486791-1637956b-ea06-489e-a20e-2e241c6aad4e.png)

**Comment by AaradhySahu** [comment]
did you find any fix??

**Comment by MrStark-XD** [comment]
Yes, now it fixed

**Comment by OBUNGE** [comment]
how do you solve thee problem
