### ISSUE TITLE
Error Proxy Connection Detected

### ISSUE THREAD

**Issue by AaradhySahu** [MrStark-XD/Edu-Mail-Generator#4]
Proxy Connection detected shows when creating openccc account can be fixed using browser as undetectable chrome which is used in this repo please edit the repo to support undetectable chrome..
https://github.com/AmmeySaini/Edu-Mail-Generator

**Comment by LogicKey** [comment]
still not working even with this undetectable chrome

**Comment by turtldoves669** [comment]
still not working I get same error.

**Comment by MrStark-XD** [comment]
Fixed
