### ISSUE TITLE
non working

### ISSUE THREAD

**Issue by LukysGaming** [MrStark-XD/Edu-Mail-Generator#5]
[*] Hold on Starting now, Keep checking this terminal for instructions
bot.py:76: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Firefox(executable_path=r'./webdriver/geckodriver')
bot.py:90: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  driver.find_element_by_xpath('//*[@id="portletContent_u16l1n18"]/div/div[2]/div/a[2]').click()
Traceback (most recent call last):
  File "bot.py", line 1040, in <module>
    main()
  File "bot.py", line 1037, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "bot.py", line 90, in start_bot
    driver.find_element_by_xpath('//*[@id="portletContent_u16l1n18"]/div/div[2]/div/a[2]').click()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 514, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //*[@id="portletContent_u16l1n18"]/div/div[2]/div/a[2]
Stacktrace:
WebDriverError@chrome://marionette/content/error.js:181:5
NoSuchElementError@chrome://marionette/content/error.js:393:5
element.find/</<@chrome://marionette/content/element.js:306:16

**Comment by MrStark-XD** [comment]
Everything fixed now

**Comment by LukysGaming** [comment]
Still
Firefox
Installed verision - 89.0.2
Latest geckodriver version - v0.30.0
Downloading...
[################################] 2612/2612 - 00:00:00
Download Successful

Chrome
Chrome isn't installed

Wich browser do you prefer to run script on

[*] 1 Firefox

Enter id ex - 1 or 2: 1
Setup Completed
 python3 bot.py

 _____    _         __  __       _ _    ____
| ____|__| |_   _  |  \/  | __ _(_) |  / ___| ___ _ __
|  _| / _` | | | | | |\/| |/ _` | | | | |  _ / _ \ '_ \
| |__| (_| | |_| | | |  | | (_| | | | | |_| |  __/ | | |_
|_____\__,_|\__,_| |_|  |_|\__,_|_|_|  \____|\___|_| |_(_)
Github Repo - https://github.com/MrStark-XD/Edu-Mail-Generator/


[*] Select a college from all available colleges to proceed....

[*] 1 - MSJC College
[*] 2 - Contra Costa College
[*] 3 - City College
[*] 4 - Sacramento College
[*] 5 - Ohlone College
[*] 6 - Cañada College
[*] 7 - Southwestern College
[*] 8 - Cuesta College
[*] 9 - American River College
[*] 10 - Antelope Valley College
[*] 11 - Bakersfield College
[*] 12 - Barstow Community College
[*] 13 - Berkeley City College
[*] 14 - Butte College
[*] 15 - Cabrillo College
[*] 16 - Calbright College
[*] 17 - Cerritos College
[*] 18 - Chabot College
[*] 19 - Skyline College
[*] 20 - Ventura College

[*] Enter college id for ex - 1 or 2 or 3.... : 5

[*] Selected College: Ohlone College

[*] Enter Your Email: letshvh@seznam.cz

[*] Performing Incapsula Bypass
[*] Fetching Token (success)
[*] Fetching Cookies (success)
[*] Sending Custom Fields and Token to Server (success)
[*] Setting Incap Token (success)
[*] Sending Custom Cookies (success)
[*] Parsing Incap Cookies (success)
[*] Interceptor Addition (success)
[*] Injecting Incap Cookies (success)

[*] Incapsula Bypass Successfull

[*] Hold on Starting now, Keep checking this terminal for instructions
Traceback (most recent call last):
  File "bot.py", line 122, in start_bot
    WebDriverWait(driver, 10).until(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
WebDriverError@chrome://marionette/content/error.js:181:5
NoSuchElementError@chrome://marionette/content/error.js:393:5
element.find/</<@chrome://marionette/content/element.js:306:16


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 1169, in <module>
    main()
  File "bot.py", line 1166, in main
    start_bot(start_url, userEmail, allColleges[userInput], userInput + 1, cookies, token)
  File "bot.py", line 126, in start_bot
    WebDriverWait(driver, 10).until(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
WebDriverError@chrome://marionette/content/error.js:181:5
NoSuchElementError@chrome://marionette/content/error.js:393:5
element.find/</<@chrome://marionette/content/element.js:306:16
