### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by terapapajani** [MrStark-XD/Edu-Mail-Generator#8]
![Screenshot 2021-12-14 234743](https://user-images.githubusercontent.com/93859919/146061185-930fadf4-a6ea-461a-a75b-500d2aec89b6.png)

**Comment by LukeWarmSodas** [comment]
i think it means that you dont have a default browser set

**Comment by nandish486** [comment]
Go for setup.py located in folder

**Comment by tithi1996** [comment]
i need in bulk ac contact telegram - samurai8454
