### ISSUE TITLE
Forbidden - You don't have permission to access this resource

### ISSUE THREAD

**Issue by rvr11** [MrStark-XD/Edu-Mail-Generator#9]
Everything works fine until the bot opens chrome. Chrome then shows the following:

"**Forbidden
You don't have permission to access this resource.

Apache/2.4.29 (Ubuntu) Server at www.openccc.net Port 443**"

After few seconds the site reloads and it says:

"Die Webseite unter https://www.openccc.net/_Incapsula_Resource?CWUDNSAI=23&xinfo=13-21526501-0%20pNNN%20RT%281640194064542%200%29%20q%280%20-1%20-1%20-1%29%20r%280%20-1%29%20B15%2814%2c0%2c0%29%20U18&incident_id=273000560031448597-75957609044184589&edet=15&cinfo=0e000000aedc&rpinfo=648&mth=GET ist eventuell vorübergehend nicht verfügbar oder wurde dauerhaft an eine neue Webadresse verschoben."

-> website is not available.

When manually opening the above link, it shows the proxy error.

I tried all options and both chrome versions. Thanks for your help.

**Comment by andrewio228** [comment]
Please help me. I am getting VPN detection

**Comment by MrStark-XD** [comment]
I'm aware of this issue, but due to lack of time I'm not able to research on it as it was fixed earlier, it needs a revised code of incap bypass

I might push an update but NO ETA as of now.
PR's are Welcome

**Comment by bozoboo** [comment]
> I'm aware of this issue, but due to lack of time I'm not able to research on it as it was fixed earlier, it needs a revised code of incap bypass
> 
> I might push an update but NO ETA as of now. PR's are Welcome

Can I pay you for an update?

**Comment by ghost** [comment]
> Please help me. I am getting VPN detection

same with me
im getting proxy/vpn detection

**Comment by rwelson** [comment]
> I'm aware of this issue, but due to lack of time I'm not able to research on it as it was fixed earlier, it needs a revised code of incap bypass
> 
> I might push an update but NO ETA as of now. PR's are Welcome

https://github.com/ultrafunkamsterdam/undetected-chromedriver  maybe this will fix the issue .

Custom Selenium Chromedriver | Zero-Config | Passes ALL bot mitigation systems (like Distil / Imperva/ Datadadome / CloudFlare IUAM)

**Comment by mylvghb** [comment]
I meet same issues @hamham26
